eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-provider/**
      service-id: provider-demo
#http://127.0.0.1:8769/api-consumer/consumer/getInterfaceInfo
    api-b:
      path: /api-consumer/**
      service-id: consumer-demo