server:
  port: 7904
spring:
  application:
    name: producer
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.99.100}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

