server:
  port: 7901
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#设置服务名
spring:
  application:
    name: provider-demo
#开启所有的监听端点
management:
  endpoints:
    web:
      exposure:
        include: "*"